Gcc warnings
countingpine/fbc pull request #1
Opened 2018-09-30 00:41 UTC by jayrm

A few more fixes for GCC warnings found on win/dos.

2018-09-30 00:45 UTC, jayrm commented
Aside from the minor fixes: thought I would try this method to submit.  I thought this an opportunity to experiment with another method for collaboration.  Apologies if this is seems overly complex, for the simple commits.

You remain in control of the pull request freebasic/fbc.  And can do whatever with the changes I am submitting to your repo, copy/paste, squash, even force push, etc.  What do you think?  On a previous pull request (last year) I pushed changes directly to the pull request.  

If the pull requester had more changes in the works, it would have interfered with their work flow.  It didn't, but still.

2018-09-30 18:03 UTC, countingpine commented
OK, so if I approve these, do they automatically carry forward to https://github.com/freebasic/fbc/pull/106?
Not sure what the pros/cons are - is the idea to avoid polluting the main thread?

2018-09-30 20:04 UTC, countingpine requested changes
Thanks for catching those extra warnings.  I'm still not sure why I or GCC was missing them.

I think this approach in the gfxlib is a good compromise, simplifying the flow while preserving the original order of execution.
We could potentially DRY out the repeated code a bit by putting the `if (has_focus){...}` block into `ToggleFullScreen()`.  I don't know if that makes logical sense, but it looks like this was the only place where it's called.

2018-09-30 20:04 UTC, countingpine commented on src/gfxlib2/win32/gfx_win32.c
> +			break;
I think this should be a `/* fall through /*` - the deleted if/break above was just to stop `WM_SIZE` falling too far through.

2018-09-30 20:04 UTC, countingpine commented on src/gfxlib2/win32/gfx_win32.c
> +			break;
Note: I don't have a Win32 build setup currently and can't test the changes.  Also, I'm not sure what key combinations this might have an effect on.

2018-09-30 20:08 UTC, countingpine commented
I opted to "request changes", which was a bit more formal looking than I'd hoped..

2018-09-30 21:11 UTC, jayrm commented
Hey Matthew,

> OK, so if I approve these, do they automatically carry forward to [freebasic#106](https://github.com/freebasic/fbc/pull/106)?

I hadn't thought about that.  It would make sense though, that it would update your gcc-warnings branch on countingpine/fbc, and then trigger another build on freebasic/fbc pull request 106.

> Not sure what the pros/cons are - is the idea to avoid polluting the main thread?

The main reason for making the pull request here, was just to try it out, see if it would be something useful to do.  My intent was that you would be able to serialize the changes.  Because if you were continuing to work on the code, and I am working on the same code, the chances of conflict will be fairly high compared to working on separate parts of the repo.

What I want, is an easy way to send you the changes.  Instead of a patch file, or email, I would just send the branch.  At the moment, though, only one way I can think of to inspect the branch locally on your machine's repo without actually merging it in publicly on github:

Fetch from the source, and create a new branch `jayrm-gcc-warnings` (for example)
`$ git fetch https://github.com/jayrm/fbc gcc-warnings:jayrm-gcc-warnings`

Then it is just another branch on your own local repo and can diff, merge, cherry-pick, or whatever.

On a couple of recent pull requests from forum members, I wish I had spent the time to research a little more.  I would have liked a way to clean up the pull request before merging in it to fbc main-line, either squashing commits, or fixing white-space, while keeping credit to the original author.

> I'm still not sure why I or GCC was missing them.

I am using gcc 7.1.0.  Possible some versions of gcc are more thorough or aggressive in checking?  I don't know.

> I opted to "request changes", which was a bit more formal looking than I'd hoped..

I think this is good.  There are several pull requests on freebasic/fbc where I created a review, except I didn't realize that you actually have to submit/accept for it to be seen by others! I just ended up deleting them later because they never got published.

Thank-you for helping me.  Besides the code changes, gives a chance to try some of github's features.  I will address the review next.  Thanks.

2018-09-30 22:32 UTC, jayrm commented on src/gfxlib2/win32/gfx_win32.c
> +			break;
Yes, correct.  It should be `/* fall through */` to the `WM_KEYDOWN|UP` handler.  I was confused by the logic there there,

Sounds good.  I moved the `if( has_focus )` to `ToggleFullScreen(EVENT *e)` just re-using the already allocated `EVENT e`.  Yeah, don't know if that's best way to express, but should behave same as before.

2018-09-30 22:45 UTC, jayrm commented
Some more thoughts:

You could also get the pull request (#1) in to your local repo with:
`$ git fetch https://github.com/countingpine/fbc pull/1/head:jayrm-gcc-warnings`

This will fetch pull request 1 and create a branch `jayrm-gcc-warnings`.  At which point it's just like another branch in your local repo.  _And you can sub in whatever `git add remote` name used for your repo instead of the full URL._  

So, if you wanted to do your own clean-up locally, git merge or rebase on to your own `gcc-warnings`,  you could do it before pushing it to the pull request 106 on freebasic/fbc.  Then just close this PR 1, because it wasn't used directly.  I might try something like that on a future PR from a forum user.

2018-10-01 21:32 UTC, countingpine approved these changes

2018-10-01 22:11 UTC, merged

2018-10-01 22:14 UTC, countingpine commented
OK, that's great.  I decided to Rebase and Merge your commits, meaning they've basically been appended to my branch, and they've been added to the original PR.

Thanks for all your help.  I might try this again some time.

2018-10-07 14:02 UTC, jayrm commented
Perfect, thanks.  I appreciate you giving your (free) time to play with this experiment.